name: waterpump-manager
base: core20
version: '0.1'
summary: Water Pump Manager Daemon
description: |
  A stub daemon for managing water supply equipment - specifically a water pump
  that controls water supply in a house.

grade: devel
confinement: strict

apps:
  daemon:
    command: waterpump_manager.py
    daemon: simple
    plugs: [network-bind]

parts:
  waterpump-manager:
    plugin: dump
    source: src

hooks:
  configure:
    plugs: [network-bind]